server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
    gateway:
      discovery:
        locator:
          enabled: true  # Habilitar el descubrimiento de rutas por Eureka
      routes:
        # Si utilizas el descubrimiento de Eureka, no necesitas definir rutas estáticas
        - id: ms-books-catalogue
          uri: lb://ms-books-catalogue  # Usa el nombre del servicio registrado en Eureka
          predicates:
            - Path=/api/books/**
        - id: ms-books-payment
          uri: lb://ms-books-payment  # Igualmente, el nombre del servicio en Eureka
          predicates:
            - Path=/api/payments/**
    management:
      endpoints:
        web:
          exposure:
            include: gateway, health, info, routes