server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Deshabilitado porque no estás usando Eureka
      routes:
        - id: ms-books-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/books/**
          filters:
            - RewritePath=/api/books/(?<segment>.*), /$\{segment} # Corrige la ruta
        - id: ms-books-payments
          uri: http://localhost:8082
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/(?<segment>.*), /$\{segment} # Corrige la ruta
    management:
      endpoints:
        web:
          exposure:
            include: gateway, health, info, routes

# Deshabilitar Eureka (ya lo tienes correcto)
eureka:
  client:
    enabled: false
  instance:
    enabled: false