server:
  port: 8081

spring:
  application:
    name: ms-books-catalogue
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  management:
    endpoints:
      web:
        exposure:
          include: gateway, health, info, routes
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    register-with-eureka: true  # Asegúrate de que el microservicio se registre en Eureka
    fetch-registry: true  # Habilita la consulta del registro de Eureka