server:
  port: 8082

spring:
  application:
    name: ms-books-payment
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  management:
    endpoints:
      web:
        exposure:
          include: gateway, health, info, routes
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/


eureka:
  instance:
    hostname: localhost  # 👈 Usa localhost en vez de la IP
    prefer-ip-address: false  # 👈 Usa el hostname en vez de la IP
  client:
    register-with-eureka: true  # Asegúrate de que el microservicio se registre en Eureka
    fetch-registry: true  # Habilita la consulta del registro de Eureka

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
